---
- hosts: all
  sudo: yes
  vars_files:
    - variables.yml
  roles:
    - apache
    # - { role: rvm_io.rvm1-ruby, tags: ruby }
  tasks:
    - name: just saying hi
      shell: echo "Hello {{yourname}}!"